uploads = []
outputs = []

[[generated]]
id = "XWwufoqpLvXvbkHE00lvO"
uri = "file://artifacts/velocity-pedals/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PTzeu1YuHhat27Pg6ZT05"
uri = "file://artifacts/velocity-pedals/assets/images/track-urban.png"
type = "image"
title = "generated_image"

[[generated]]
id = "a8RN_gM8CcKaEaJZsTwbS"
uri = "file://artifacts/velocity-pedals/assets/images/track-alpine.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gKzHBNrGcdGLVAHjKxX1X"
uri = "file://artifacts/velocity-pedals/assets/images/track-coastal.png"
type = "image"
title = "generated_image"
